package com.syngenta.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import org.springframework.data.annotation.Id;

public class Contact implements Serializable, Comparable<Contact> {

	@Id

	@GeneratedValue(strategy = GenerationType.IDENTITY)

	private int id; // id field is an identity field as well as generated by database

@Column(name = "firstname")

private String name;

@Column(name = "lastname")

private String lastname;



	public int getId() {
	return id;
}

public void setId(int id) {
	this.id = id;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public String getLastname() {
	return lastname;
}

public void setLastname(String lastname) {
	this.lastname = lastname;
}

	public Contact() {

// default constructor is needed since we are using jpa

	}

	@Override
	public int compareTo(Contact o) {
		// TODO Auto-generated method stub
		return 0;
	}

}